endpoint = 'database-2.czlbzbpdgtgg.us-east-1.rds.amazonaws.com'
port = '5432'
user = 'postgres'
pwd = 'postgres25thDynasty'
db_name = 'sub_saharan'

remote_db_endpoint = 'conflict-africa.c7biawpsnxhf.us-east-2.rds.amazonaws.com'
remote_db_port = '5432'
remote_db_user = 'postgres'
remote_db_pwd = 'Project3!'
remote_db_name = 'postgres'